### ISSUE TITLE
Some Bugs

### ISSUE THREAD

**Issue by kingiw** [africamonkey/Training_Summary_Python#31]
1. Redirecting to `accounts/profile/`  after logging in successfully caused an error.
2. When log out, the visits to templates which refers to `user.xxx` raise errors.

**Comment by Dexan-Ou** [comment]
2. actually, it's not user.** it's get_user() or request.user

**Comment by Dexan-Ou** [comment]
2. well, i found what casue this error, user.id is not passed from views.py, it is called directly in templates, thus you shouldn't render the *Add/Edit Summary* button as it is inaccessible for guest

**Comment by Dexan-Ou** [comment]
all fix
